version: "3"
services:
  app:
    build:
      context: .
    ports:
      - "4000:4000"
    command: yarn server:watch
    environment:
      MONGO_URI: mongodb://mongo:27017/app_test
      JOB_QUEUE_REDIS_URI: redis://redis:6379
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:4.0
    volumes:
      - mongo:/data/db
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE=app_test
    ports:
      - "27017:27017"
    command: mongod --smallfiles --logpath=/dev/null
  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
    logging:
      driver: none
volumes:
  mongo: ~
